### ISSUE TITLE
Not working anymore 

### ISSUE THREAD

**Issue by leodoi3** [buzz/imdb-link-em-all#56]
I'm using this script under Brave with TM 4.13 and since today it just stopped working.  I tried re-toggling the script, manually update it and it didn't help.

**Comment by NoobPro404** [comment]
same here... Not working :-(

**Comment by davix004** [comment]
Hello! Unfortunately, I suffer from the same problem too, it doesn't work anymore since I install the 2.0.10 version of the script. My OS is windows 10 1803 x64, script intalled in Tampermonkey 4.13 under Firefox 96.0b10. The error retrieved is "Uncaught Error: LTA: Could not find target container!". I tried with disabled extensions, delete and reinstall the script, but the result is the same.

**Comment by buzz** [comment]
Might be IMDb changed their layout again. Will have to check this.

**Comment by davix004** [comment]
The temporary workaround that I found is to add /reference at the end of the url like [https://www.imdb.com/title/tt10272386/reference](url) instead of [https://www.imdb.com/title/tt10272386](url), and the script run perfectly.

**Comment by buzz** [comment]
The new version v2.0.11 should fix it.
